### ISSUE TITLE
Setup and configure PNPM and Node

### ISSUE THREAD

**Issue by patryk-szydlowski** [moneyhut/moneyhut#2]
```[tasklist]
### Tasks
- [x] Require certain PNPM versions to run the project
- [x] Pin Node version using PNPM
- [x] Setup CI workflow to install Node and project dependencies
- [ ] Add documentation on how to get started with the project
```
