### ISSUE TITLE
Setup formatting tools

### ISSUE THREAD

**Issue by patryk-szydlowski** [moneyhut/moneyhut#3]
```[tasklist]
### Tasks
- [x] Setup EditorConfig
- [x] Setup and configure Prettier
- [x] Add CI workflow to check for formatting issues using Prettier
- [ ] Add documentation on how to setup Prettier for your IDE
```
